### ISSUE TITLE
Image missing and Statistics tabs is empty

### ISSUE THREAD

**Issue by qwervbnm** [koliva8245/HeroesParserData#3]
First of all , thank you for developing this application. It's a big big surprise for me to find this application. Really helpful and convenient to use.

But I found that every hero portrait is missing. I'm from china , so I think it's because the hero name in replay files is in chinese, and also map name is.

for example, the following sentence is from _ImageMissingLog.txt. the name "诺娃" means "nova".

> [48297] Leader hero portrait: 诺娃

If possible, can you fix these issues because of language difference? Maybe every hero has an ID so you can specific them no matter which language is. If not, just tell me, I can write a hero and map name list from chinese to english. 

 I think it's same reason caused statistics tabs empty. Every stats value is zero because the hero and map stats is counted by english name.

**Comment by koliva8245** [comment]
I don't think its just the hero names. Its probably the talent names, awards names too, and some other names/values too.

If you could take screenshots of the following in the RawData tab it would be helpful: Replays, Player Heroes, Match Players, Match Team Bans, Match Player Talent, Match Messages, and Match Awards.

Overall, supporting different languages is going to a pain, but I'll see what I can do.

**Comment by koliva8245** [comment]
If you can send me one your replays too, that would be nice.

**Comment by koliva8245** [comment]
Never mind about the screenshots and the replay file.  The language issue should be fixed (for the most part)  Download version 1.4.4.  

The hero names and maps are translated to their English name before being saving into the database.  If an unknown hero/map name is found the replay will fail to parsed.  You will then need to look into the log files and find the offending hero/map name.

**Comment by qwervbnm** [comment]
It worked, nice done. 

In version 1.4.3 , the hero/map names is in chinese and the talent/awards names is in english. Now they are all in english and worked fine.

Anyway, I send you some replays for sample. If  you need, you can check or test in future.

[replays.txt](https://github.com/koliva8245/HeroesParserData/files/708298/replays.txt)
(I don't know why I can't upload zip file. So I changed the filename extension to "txt". Just change back and you can open it. )
