### ISSUE TITLE
Version 1.54 does not start anymore

### ISSUE THREAD

**Issue by giucesar** [koliva8245/HeroesParserData#4]
Version 1.54 does not start anymore; it freezes on the main screen.

**Comment by koliva8245** [comment]
The start up screen? I need to see the _StartupLog.txt which is in
`
%LocalAppData\HeroesParserData\app-<Version>\logs\
`

**Comment by giucesar** [comment]
[03/19/2017 18:27:17 PM] Performing database migration
[03/19/2017 18:27:18 PM] Checking for updates...
[03/19/2017 18:27:19 PM] Already latest version
[03/19/2017 18:27:19 PM] Initializing Hero Icons
[03/19/2017 18:27:19 PM] Initializing Heroes Parser Data
[03/19/2017 18:27:21 PM] Starting Heroes Parser Data

**Comment by koliva8245** [comment]
Any other logs in that folder (excluding DatabaseMigrateLog.txt, UpdateLog.txt, _ImageMissingLog.txt, or _ReferenceNameLog.txt)?

Those logs showed that the application did start.  So it "froze" on that Home tab, which shows Total Games, Season Games, etc?

**Comment by giucesar** [comment]
I have three files, DatabaseMigrateLog.txt, _StartupLog.txt and UpdateLog.txt. That is all. Windows 10 64bits if it helps.

Database
[03/19/2017 18:27:18 PM] Current Version: 4
[03/19/2017 18:27:18 PM] Required Version: 4
[03/19/2017 18:27:18 PM] No migration required

Update
[03/19/2017 18:27:19 PM] Update Check
[03/19/2017 18:27:19 PM] Current Version: 1.5.4
[03/19/2017 18:27:19 PM] Latest Version: 1.5.4

**Comment by koliva8245** [comment]
On that screen, is there any data being shown?  For example for Replays in Database there's a number besides zero.

Also what version did you update from? Have you tried deleting/removed the application and reinstalling (be sure to save a copy of your database).

**Comment by giucesar** [comment]
Everything 0. But after I updated from 1.53 to 1.54 and it started to freeze, I did a clean install and probably lost my database.

**Comment by koliva8245** [comment]
I have no idea why its freezing for you. Everything is working fine for me. If version 1.5.3 was working for you then 1.5.4 should be fine as well.  Only two very minor commits were made for that version.

**Comment by giucesar** [comment]
I ran as admin and it worked. I'll try a clean install again, clearly something in my user has a conflict.

**Comment by giucesar** [comment]
Installed again, still freezing. Only running as admin it works.

**Comment by koliva8245** [comment]
Interesting.

Can you run HeroesParserData.exe from inside the installed folder instead of running the shortcut?

**Comment by giucesar** [comment]
Freezes as well.

**Comment by koliva8245** [comment]
Weird. Having admin privileges shouldn't make a difference.  Something must be configured for your windows account that's causing an issue or something.

**Comment by giucesar** [comment]
FYI, now it came back to work. It must be a problem with windows 10 and .Net framework.
